

const actionTypes  = {

        FETCH_PRODUCTS_REQUEST : 'FETCH_PRODUCTS_REQUEST',
        FETCH_PRODUCTS_SUCCESS : 'FETCH_PRODUCTS_SUCCESS',
        FETCH_PRODUCTS_FAIL : 'FETCH_PRODUCTS_FAIL',
        CLEAR_ERROR: 'CLEAR_ERROR',
        
        GET_PRODUCT_DETAILS_SUCCESS : 'GET_PRODUCT_DETAILS_SUCCESS',
        GET_PRODUCT_DETAILS_FAIL : 'GET_PRODUCT_DETAILS_FAIL',
        GET_PRODUCT_DETAILS_REQUEST :'GET_PRODUCT_DETAILS_REQUEST',

        GET_PRODUCTS_FAIL : 'getProductsFail',
        GET_PRODUCTS_SUCCESS : 'getProductsSuccess',
        ADD_TO_CART:"addtoCart",
        REMOVE_TO_CART: "removetoCard",
        CART_RESET:"CART_RESET",
        ADD_TO_CART_ERROR : "ADD_TO_CART_ERROR",
        USER:"USER",
        ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
        REMOVE_TO_WISHLIST : "REMOVE_TO_WISHLIST",
        REMOVE_ALL_TO_CART:"REMOVE_ALL_TO_CART",
        USER_PROFILE_PIC: "USER_PROFILE_PIC"
}

export default actionTypes